package com.br.produtomvp.view;

import javax.swing.JLabel;
import javax.swing.JMenuItem;

/**
 *
 * @author tetzner
 */
public final class PrincipalProdutoView extends javax.swing.JFrame {

    /**
     * Creates new form TelaPrincipalView
     */
    public PrincipalProdutoView() {
        initComponents();
    }

    public JMenuItem getMnuItemIncluir() {
        return mnuItemIncluir;
    }

    public JMenuItem getMnuItemListarProdutos() {
        return mnuItemListarProdutos;
    } 

    public JLabel getLblQuantidadeProdutos() {
        return lblQuantidadeProdutos;
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTotalProdutos = new javax.swing.JLabel();
        lblQuantidadeProdutos = new javax.swing.JLabel();
        mnuGerenciarProduto = new javax.swing.JMenuBar();
        mnuIncluir = new javax.swing.JMenu();
        mnuItemIncluir = new javax.swing.JMenuItem();
        mnuItemListarProdutos = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Tela Principal de Produto");
        setResizable(false);

        lblTotalProdutos.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        lblTotalProdutos.setText("Total de produtos:");

        lblQuantidadeProdutos.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        lblQuantidadeProdutos.setText("0");

        mnuGerenciarProduto.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N

        mnuIncluir.setText("Produto");

        mnuItemIncluir.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        mnuItemIncluir.setText("Incluir");
        mnuIncluir.add(mnuItemIncluir);

        mnuItemListarProdutos.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        mnuItemListarProdutos.setText("Listar");
        mnuIncluir.add(mnuItemListarProdutos);

        mnuGerenciarProduto.add(mnuIncluir);

        setJMenuBar(mnuGerenciarProduto);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(438, Short.MAX_VALUE)
                .addComponent(lblTotalProdutos)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblQuantidadeProdutos)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 104, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblQuantidadeProdutos)
                    .addComponent(lblTotalProdutos)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel lblQuantidadeProdutos;
    private javax.swing.JLabel lblTotalProdutos;
    private javax.swing.JMenuBar mnuGerenciarProduto;
    private javax.swing.JMenu mnuIncluir;
    private javax.swing.JMenuItem mnuItemIncluir;
    private javax.swing.JMenuItem mnuItemListarProdutos;
    // End of variables declaration//GEN-END:variables
}
