package com.br.produtomvp.view;

import javax.swing.JLabel;
import javax.swing.JMenuItem;

/**
 *
 * @author tetzner
 */
public final class PrincipalProdutoView extends javax.swing.JFrame {

    /**
     * Creates new form TelaPrincipalView
     */
    public PrincipalProdutoView() {
        initComponents();
    }

    public JMenuItem getMnuItemIncluir() {
        return mnuItemIncluir;
    }

    public JMenuItem getMnuItemListarProdutos() {
        return mnuItemListarProdutos;
    } 

    public JLabel getLblQuantidadeProdutos() {
        return lblQuantidadeProdutos;
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem5 = new javax.swing.JMenuItem();
        lblTotalProdutos = new javax.swing.JLabel();
        lblQuantidadeProdutos = new javax.swing.JLabel();
        mnuBarProduto = new javax.swing.JMenuBar();
        mnuProduto = new javax.swing.JMenu();
        mnuItemIncluir = new javax.swing.JMenuItem();
        mnuItemListarProdutos = new javax.swing.JMenuItem();
        mnuGerenciarLog = new javax.swing.JMenu();
        mnuItemJSON = new javax.swing.JMenuItem();
        mnuItemXML = new javax.swing.JMenuItem();
        mnuDB = new javax.swing.JMenu();
        mnuItemSQLite = new javax.swing.JMenuItem();

        jMenuItem5.setText("jMenuItem5");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Tela Principal de Produto");
        setResizable(false);

        lblTotalProdutos.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        lblTotalProdutos.setText("Total de produtos:");

        lblQuantidadeProdutos.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        lblQuantidadeProdutos.setText("0");

        mnuBarProduto.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N

        mnuProduto.setText("Produto");

        mnuItemIncluir.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        mnuItemIncluir.setText("Incluir");
        mnuProduto.add(mnuItemIncluir);

        mnuItemListarProdutos.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        mnuItemListarProdutos.setText("Listar");
        mnuProduto.add(mnuItemListarProdutos);

        mnuBarProduto.add(mnuProduto);

        mnuGerenciarLog.setText("Configurar Log");

        mnuItemJSON.setText("JSON");
        mnuGerenciarLog.add(mnuItemJSON);

        mnuItemXML.setText("XML");
        mnuGerenciarLog.add(mnuItemXML);

        mnuDB.setText("DB");

        mnuItemSQLite.setText("SQLite");
        mnuDB.add(mnuItemSQLite);

        mnuGerenciarLog.add(mnuDB);

        mnuBarProduto.add(mnuGerenciarLog);

        setJMenuBar(mnuBarProduto);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(438, Short.MAX_VALUE)
                .addComponent(lblTotalProdutos)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblQuantidadeProdutos)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 104, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblQuantidadeProdutos)
                    .addComponent(lblTotalProdutos)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JLabel lblQuantidadeProdutos;
    private javax.swing.JLabel lblTotalProdutos;
    private javax.swing.JMenuBar mnuBarProduto;
    private javax.swing.JMenu mnuDB;
    private javax.swing.JMenu mnuGerenciarLog;
    private javax.swing.JMenuItem mnuItemIncluir;
    private javax.swing.JMenuItem mnuItemJSON;
    private javax.swing.JMenuItem mnuItemListarProdutos;
    private javax.swing.JMenuItem mnuItemSQLite;
    private javax.swing.JMenuItem mnuItemXML;
    private javax.swing.JMenu mnuProduto;
    // End of variables declaration//GEN-END:variables
}
